'use client'
import { useEffect,useMemo,useState } from 'react'
import { AppNav } from '@/components/AppNav'
import { createClient } from '@/lib/supabase/client'
import { calculateAdherence,type SessionStatus } from '@/lib/engine/adherence'
import { generateMonthlyReview } from '@/lib/engine/review'

type ReviewRow={id:string;recommendation:string;reasons:string[];adherence_percent:number;accepted_at?:string;created_at:string}
export default function ReviewPage(){
 const [statuses,setStatuses]=useState<SessionStatus[]>([]);const [pain,setPain]=useState(0);const [replacements,setReplacements]=useState(0);const [progressing,setProgressing]=useState(0);const [history,setHistory]=useState<ReviewRow[]>([]);const [programId,setProgramId]=useState<string>();
 useEffect(()=>{void load()},[])
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const since=new Date(Date.now()-28*86400000).toISOString();const [sessions,pains,repls,progress,program,reviews]=await Promise.all([s.from('workout_sessions').select('status').eq('user_id',user.id).gte('created_at',since),s.from('pain_logs').select('id',{count:'exact',head:true}).eq('user_id',user.id).gte('created_at',since),s.from('exercise_replacements').select('id',{count:'exact',head:true}).eq('user_id',user.id).gte('created_at',since),s.from('progression_records').select('state').eq('user_id',user.id).gte('created_at',since),s.from('programs').select('id').eq('user_id',user.id).eq('status','active').maybeSingle(),s.from('program_reviews').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5)]);setStatuses((sessions.data??[]).map((x:any)=>x.status).filter((x:any)=>['completed','partial','missed','in_progress'].includes(x)));setPain(pains.count??0);setReplacements(repls.count??0);const rows=progress.data??[];setProgressing(rows.length?Math.round(rows.filter((x:any)=>['Ready to Increase','Building Reps'].includes(x.state)).length/rows.length*100):0);setProgramId(program.data?.id);setHistory((reviews.data??[]) as ReviewRow[])}
 const adherence=useMemo(()=>calculateAdherence(statuses),[statuses]);const result=useMemo(()=>generateMonthlyReview({adherencePercent:adherence.percent,painEvents:pain,progressingExercisePercent:progressing,replacementCount:replacements,averageDurationVarianceMinutes:0}),[adherence,pain,progressing,replacements])
 async function saveReview(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const end=new Date(),start=new Date(Date.now()-28*86400000);await s.from('program_reviews').insert({user_id:user.id,program_id:programId,review_period_start:start.toISOString().slice(0,10),review_period_end:end.toISOString().slice(0,10),adherence_percent:adherence.percent,pain_events:pain,progressing_exercise_percent:progressing,replacement_count:replacements,recommendation:result.recommendation,reasons:result.reasons,accepted_at:new Date().toISOString()});await load()}
 return <main className="container"><AppNav/><div className="eyebrow">Four-week review</div><h1>Your programme check-in</h1><div className="metric-grid"><div className="card"><div className="eyebrow">Adherence</div><div className="metric">{adherence.percent}%</div></div><div className="card"><div className="eyebrow">Progressing</div><div className="metric">{progressing}%</div></div><div className="card"><div className="eyebrow">Pain events</div><div className="metric">{pain}</div></div><div className="card"><div className="eyebrow">Replacements</div><div className="metric">{replacements}</div></div></div><section className="card review-result"><div className="eyebrow">Recommendation</div><h2>{result.recommendation}</h2>{result.reasons.map(reason=><p className="muted" key={reason}>{reason}</p>)}<button className="btn btn-primary" onClick={saveReview}>Accept Recommendation</button></section><h2>Previous reviews</h2><div className="stack">{history.map(row=><div className="card row" key={row.id}><div><strong>{row.recommendation}</strong><div className="muted">{new Date(row.created_at).toLocaleDateString('en-GB')}</div></div><span className="pill">{row.adherence_percent}% adherence</span></div>)}{!history.length&&<div className="card empty">Your first saved review will appear here.</div>}</div></main>
}
