import Link from 'next/link'
import { ArrowRight, BarChart3, BrainCircuit, Check, Dumbbell, ShieldCheck, Sparkles } from 'lucide-react'

export default function Landing(){return <main className="marketing-shell">
<header className="marketing-nav"><Link href="/" className="brand"><span className="brand-mark">R</span>RepFlow</Link><nav><a href="#how">How it works</a><a href="#features">Features</a><a href="#pricing">Pricing</a></nav><div><Link className="nav-login" href="/login">Log in</Link><Link className="nav-cta" href="/demo">Try live demo</Link></div></header>
<section className="landing-hero"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={15}/> Adaptive training, built around you</div><h1>Stop guessing.<br/><span>Start progressing.</span></h1><p>RepFlow builds your program, tracks every set and adjusts your next target automatically—without spreadsheets or generic templates.</p><div className="hero-actions"><Link className="primary-cta" href="/demo">Try the live demo <ArrowRight size={18}/></Link><Link className="secondary-cta" href="/signup">Create account</Link></div><div className="trust-row"><span><Check size={15}/> Science-based programming</span><span><Check size={15}/> No credit card for demo</span></div></div><div className="product-mockup"><div className="mockup-glow"/><div className="phone-card"><div className="phone-head"><span>Today</span><b>Upper A</b></div><div className="phone-score"><div><small>SESSION SCORE</small><strong>94</strong></div><span>Ready</span></div>{['Barbell Bench Press','Chest-Supported Row','Seated DB Press'].map((name,i)=><div className="phone-exercise" key={name}><span>{i+1}</span><div><b>{name}</b><small>{i===0?'4 × 6–8':'3 × 8–10'}</small></div><Check size={16}/></div>)}<div className="phone-button">Start workout</div></div><div className="floating-card float-progress"><BarChart3/><div><small>WEEKLY PROGRESS</small><strong>+12%</strong></div></div><div className="floating-card float-adapt"><BrainCircuit/><div><small>NEXT TARGET</small><strong>+2.5 kg</strong></div></div></div></section>
<section className="proof-strip"><span>Built for real training</span><strong>Personalised</strong><strong>Adaptive</strong><strong>Evidence-led</strong><strong>Simple</strong></section>
<section id="how" className="marketing-section"><div className="section-heading"><p className="eyebrow">HOW IT WORKS</p><h2>Your training system in three steps.</h2><p>No complicated setup. Tell us what you need and start training.</p></div><div className="steps-grid">{[[Dumbbell,'01','Tell us about you','Goal, experience, schedule and available equipment.'],[BrainCircuit,'02','Get your program','RepFlow creates balanced sessions matched to your constraints.'],[BarChart3,'03','Train and adapt','Log sets. Your next targets update from real performance.']].map(([Icon,n,title,text]:any)=><article className="feature-card" key={n}><div className="feature-icon"><Icon/></div><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section id="features" className="marketing-section split-feature"><div><p className="eyebrow">BUILT DIFFERENTLY</p><h2>A program that responds to your training.</h2><p>Generic PDFs cannot react when you outperform a target, miss a session or need an exercise replacement. RepFlow can.</p><ul className="check-list"><li><ShieldCheck/> Safety and fatigue guardrails</li><li><BrainCircuit/> Automatic load and rep targets</li><li><Dumbbell/> Equipment-aware exercise selection</li><li><BarChart3/> Clear progress history</li></ul></div><div className="adaptation-panel"><div className="adaptation-head"><span>LAST WORKOUT</span><b>Bench Press</b></div><div className="adaptation-result"><small>PERFORMANCE</small><strong>70 kg × 8, 8, 8, 8</strong></div><div className="adapt-arrow">↓</div><div className="adaptation-next"><small>NEXT TARGET</small><strong>72.5 kg × 6–8</strong><span>Load increased</span></div></div></section>
<section id="pricing" className="pricing-cta"><div><p className="eyebrow">START WITH THE DEMO</p><h2>See the full athlete experience now.</h2><p>Complete the short assessment, open your dashboard and log a real sample workout.</p></div><Link className="primary-cta" href="/demo">Launch interactive demo <ArrowRight size={18}/></Link></section>
<footer className="marketing-footer"><Link href="/" className="brand"><span className="brand-mark">R</span>RepFlow</Link><span>Adaptive strength training.</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></footer>
</main>}
